baseURL = "https://rosieafisher.com/"
languageCode = "en-us"
title = "Rosie Fisher"
theme = "minimal"

[params]
  defaultTheme = "light"
  backgroundColor = "#f4f0e8"
  css = ["/css/custom.css"]
  profilePic = "/images/taos_cover4.jpeg"
  tagline = "rosie fisher: terrestial systems modeling"

  [[params.contactLinks]]
    name = "bluesky"
    url = "https://bsky.app/profile/rosieafisher.bsky.social"
    icon = "/images/icons/bluesky.svg"

  [[params.contactLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/rosie-fisher-4416b719/"
    icon = "/images/icons/linkedin.svg"

  [[params.contactLinks]]
    name = "cicero"
    url = "https://cicero.oslo.no/en/employees/rosie-fisher"
    icon = "/images/icons/cicero.png"

  [[params.contactLinks]]
    name = "google scholar"
    url = "https://scholar.google.com/citations?user=YOJpkTcAAAAJ&hl=en"
    icon = "/images/icons/google-scholar.svg"

  [[params.contactLinks]]
    name = "orcid"
    url = "https://orcid.org/0000-0003-3260-9227"
    icon = "/images/icons/orcid.svg"

  [menu]

  [[menu.main]]
    name = "home"
    url = "/"
    weight = 0

  [[menu.main]]
    name = "cv"
    url = "/cv/"
    weight = 1

      [[menu.main]]
    name = "publications"
    url = "/publications/"
    weight = 2

     [[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = 3

    [[menu.main]]
      name = "bio"
      url = "/bio/"
      weight = 4

  [[menu.main]]
    name = "research"
    url = "/research/"
      weight = 5

  [[menu.main]]
    name = "network"
    url = "/team/"
    weight = 6

  
